## Part 1: Getting started with Python

The world is full of problems. All sorts of problems, really. And sometimes it falls on us, as individuals or as small groups, to solve one of these problems.

Fortunately, we humans are pretty smart: we're good at figuring out what to do, and we're often good at doing it too. But so are most other primates, and crows, and beavers, and dolphins... so, why are we _smarter_ than them?

Well, we have evolved to have two big advantages over everyone else:

* We're good at building tools, which we can then use to help us do things
* We're good (like, _really_ good) at communicating: ideas, instructions, questions, explanations...

So imagine how amazing it would be if we could _communicate with our tools_!

Well... that is exactly what coding is, and it is exactly what we're about to do.

### 1.1 Making things

> "You can make anything by writing" - C.S. Lewis

Writing code is like writing a novel, or creating any other piece of art. You start with a blank canvas, and then gradually you start to add things to it.

Let's have a look at some of the things we can start building with.

In [2]:
3

3

In [3]:
3 + 4

7

In [4]:
"hi"

'hi'

Most "things" in Python are **objects**. An **object** here in Python is the same as an object in real life: it has certain properties, you can do things to it, you can use it to do things...

Moreover, every object belongs to a certain **type** - like granite is a type of rock, or jazz is a type of music. For example, we've just seen an **integer** object:

In [5]:
type(3)

int

And a **string** object:

In [6]:
type("hi")

str

We can change the type of some objects - for example, we can turn an integer into a string:

In [7]:
str(3 * 5)

'15'

Notice the quote marks in the printed output?

Or we can turn this particular string into an integer:

In [8]:
int("10")

10

But what about this one...?

In [9]:
int("hi")

ValueError: invalid literal for int() with base 10: 'hi'

Python didn't let us do that, but think about why. Can you think of a sensible way to turn `"hi"` into an integer? (Oi, you, trying to add up letter scores or whatever it is you're doing over there. I said a _sensible_ way.)

Similarly, it won't let us "add together" an integer and a string:

In [10]:
10 + "hi"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

Instead of an answer, we get an **error message** telling us what went wrong. Look at the last line: Python is helpfully telling us that we tried to add a `str` and an `int`, and that `+` won't work with that combination!

#### Exercise

1. What happens if we "add together" two strings?
2. Fix the `10 + "hi"` example: change the type of the integer so that we can add a string to it.
2. We can't add together an integer and a string, but what about multiplication?
3. Try out some more maths. Can you find another type of object?

### 1.2 Keeping things

> "Save it for later" - The Beat

Sure, these things we're making are great, but they're just kind of... _there_. Wouldn't it be nice if we could give each of them a name?

In [11]:
result = 3 + 4

Nothing seemed to happen. But something _did_ happen...

In [12]:
result

7

Our thing, our integer, our `7`, has been **assigned** to an object called `result`. So `result` is the name of this object (which is an integer with the value of `7`). And whenever we ask for `result`, we will get `7` in return. Makes sense?

Let's make another integer object:

In [13]:
to_add = 10

So `result` is an integer, and `to_add` is an integer, So... we should be able to add them together, right?

In [14]:
total = result + to_add

total

17

Let's revise what we already know about strings too:

In [15]:
sentence = "Your answer is: "
message = sentence + str(total)

message

'Your answer is: 17'

There's one more super-useful type of object which we should look at: **lists**.

Lists are like containers which let you keep multiple things in the same place.

In [16]:
letters = ["a", "b", "c", "d", "e", "f", "g"]

letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

We can go back and **slice** things out of lists based on their position. But...

    |￣￣￣￣￣￣￣￣￣| 
    |    WARNING    | 
    |    ~~~~~~~    | 
    | Python starts |
    |   counting    |
    |    from 0     | 
    |＿＿＿＿＿＿＿＿＿| 
    (\__/) || 
    (•ㅅ•) || 
    / 　 づ

(There are reasons for this, which you can go and read about if you're interested.)

In [17]:
letters[0]

'a'

In [18]:
letters[2]

'c'

Negative positions count backwards from the end of the list.

In [19]:
letters[-2]

'f'

You can also slice a whole section of a list using the format `from:upto`. But bear in mind that "up to" means "up to and NOT including".

In [20]:
letters[0:3]

['a', 'b', 'c']

If you don't tell Python where to stop, it will assume you want to go up to the end of the list:

In [21]:
letters[4:]

['e', 'f', 'g']

Similarly, if we don't say where we want to start, Python assumes we want to start at the very beginning, a very good place to start. Remember what negative positions do?

In [22]:
letters[:-2]

['a', 'b', 'c', 'd', 'e']

#### Exercises

1. Make an object called `python_ability`: an integer which you think represents your Python skill level right now
2. What happens if we assign over the top of an object that already exists? Try reassigning `python_ability` as `python_ability + 1`
3. Now combine `python_ability` with a string containing a motivational message to yourself. You're doing great!
4. Do all the things in a list need to be of the same type? Try things out... can you put a _list_ inside a list?
5. What does `letters[0:6:2]` do? What about `letters[::-1]`?
6. What happens if you slice a string?

### 1.3 Comparing things

> "All animals are equal, but some animals are more equal than others" - George Orwell

Now we've got the hang of objects, let's look at some useful things we can do with them. **Comparison operators** let us make comparisons between two objects (astonishing, right?). A comparison will always give us back a **Boolean** (or **logical**) value. Sounds fancy, but it just means `True` or `False`.

In [23]:
3 == 3

True

In [24]:
3 != 3

False

Here are all the comparison operators:

| Operator | Meaning                  |
|----------|--------------------------|
| `==`     | equals                   |
| `!=`     | not equal                |
| `<`      | less than                |
| `>`      | greater than             |
| `<=`     | less than or equal to    |
| `>=`     | greater than or equal to |

The only slightly tricky one to remember is `==` for checking equality. Why `==`, rather than just plain `=`? Maybe you've already realised...

In [25]:
3 = 4

SyntaxError: can't assign to literal (<ipython-input-25-effb9ca1a7d0>, line 1)

Remember `=` already does something - assignment! We just tried to tell Python that `3` is now `4`, and Python told us we tried to do something stupid.

We can compare other types of object too, as well as numbers. For example, Boolean values have numeric equivalents: `False` is a "logical 0", and `True` is a "logical 1":

In [26]:
False == 0

True

In [27]:
True > False

True

We can also "compare" strings:

In [28]:
"python" == "matlab"

False

In [29]:
"python" > "matlab"

True

#### Exercises

1. Play around with numerical comparisons until you're happy with them!
2. What happens if you add two Booleans together?
2. Are uppercase letters the same as lowercase letters?
3. Why is `"python"` greater than `"matlab"`? Write a 6000 word essay explaining... just kidding. But can you actually figure out what's going on?

### 1.4 Controlling things

> "If I could, then I would" - The Calling

**Question:** When you enter a room, do you turn on the light?

> **A)** Yes, always, I hate the planet

> **B)** No, never, I am a creature of the dark

> **C)** I dunno, sometimes?

If you chose A, STOP IT YOU TERRIBLE PERSON.

If you chose B, fair enough, you do you.

If you chose C (you _probably_ chose C, right?), perhaps you consider a couple of things before you decide whether to turn on the light or not. Is the room being used? Is the light already turned on? If not, how dark is it?

In other words, your next move depends on something else... let's set the scene and create an object storing the current "status" of our light - i.e. whether the light is on or not. (Objects like this, where the value is going to change, are sometimes referred to as **variables**.)

In [30]:
light_status = "on"

Let's pretend we are Person B, the one who likes the dark. If the light is on, we turn it off, no further questions.

In [31]:
if light_status == "on":
    light_status = "off"

light_status

'off'

What just happened? Let's risk getting yelled at by Person B and shed some light on the situation.

First, Python saw the `if` keyword, which tells it to check the **condition** which comes immediately afterwards. Here, our condition was `light_status == "on"`. This `if CONDITION:` structure is called an **`if`-statement**.

A condition must always be a Boolean, i.e. `True` or `False`. Our equality comparison gave us `True`, because remember that just a moment ago we set `light_status = "on"`!

Then, because our condition was `True`, we ran the indented code underneath the `if`-statement. Here, that was just the single line `light_status = "off"`, but you can put as much code as you like within this **`if`-clause**, as long as every line is indented by the same amount. Technically this _could_ be any amount, but everyone (yes, _everyone_) uses 4 spaces, so stick to that.

If our condition had been `False`, we would have skipped the indented lines completely, and carried on as usual from just after the indented section. Let's try that out...

In [32]:
if 1 == 2:
    word = "banana"
    light_status = 1000*word

light_status

'off'

Now, how about we pretend we're Terrible Person A, and if the light is off, without a second thought we turn it on?

Sure, one way of doing this is by changing our condition from `light_status == "on"` to `light_status == "off"`:

In [33]:
light_status = "off"

if light_status == "off":
    light_status = "on"

light_status

'on'

We could actually have re-used our old Person B condition though, by combining it with `not`. All `not` does is flip between `True` and `False`.

In [34]:
not False

True

So using `not`, we can create a person even worse than Person A, who _always_ finds a way to turn on the light.

In [35]:
light_status = "whatever"

if not light_status == "on":
    light_status = "on"

light_status

'on'

We urgently need someone sensible to take control of the situation. Time to build Person C.

Person C always checks two things. They check whether the light is on, and how bright the room is. If the light is not on already and it's too dark, Person C turns the light on. Otherwise, Person C turns the light off.

In [36]:
light_status = "whatever"
brightness = 2

if not light_status == "on" and brightness < 5:
    light_status = "on"
else:
    light_status = "off"

light_status

'on'

Two things to note here. Firstly, our condition had multiple parts:

* `not light_status == "on"`
* `brightness < 5`

In Python, there are three **logical operators** which we can use when we work with Booleans. We've seen `not` already, which "flips" a Boolean. The other two are `and`, which stays `True` if _everything_ is `True`, and `or`, which stays `True` if _something_ is `True`:

| `and`     | **True**  | **False** |
|-----------|-----------|-----------|
| **True**  | `True`    | `False`   |
| **False** | `False`   | `False`   |

| `or`     | **True**  | **False** |
|-----------|-----------|-----------|
| **True**  | `True`    | `True`    |
| **False** | `True`    | `False`   |

In our case, we needed _both_ parts of our condition to be `True`, so we combined them using `and`.

Secondly, we added an **`else`-clause** to our `if`-clause. This lets us provide Python with an alternative block of code, which it runs if it _doesn't_ run the `if`-block. See the difference when we run the same if-else combo for a brighter room:

In [37]:
light_status = "whatever"
brightness = 8

if not light_status == "on" and brightness < 5:
    light_status = "on"
else:
    light_status = "off"

light_status

'off'

So we can split our code into two cases quite easily. But why stop at two cases? What if you have MORE cases?

You might try "nesting" `if`-statements...

    if CONDITION:
        do something
    else:
        if ANOTHER_CONDITION:
            do a different thing
        else:
            do something else entirely

This works, but a much nicer way of doing it is with `elif`. Yes, that is an `else` smashed together with an `if`. Yes, it is a real thing. Try playing around with the brightness level below.

In [38]:
brightness = 12

if brightness < 5:
    light_status = "on"
    curtains_status = "closed"
    
elif brightness <= 8:
    light_status = "off"
    curtains_status = "open"
    
elif brightness < 9000:
    light_status = "off"
    curtains_status = "closed"
    
else:
    light_status = "It's OVER 9000!!!"
    curtains_status = "Hassen ijou da?!?!"

"light: " + light_status + ", curtains: " + curtains_status

'light: off, curtains: closed'

#### Exercises

1. Choose 5 integers that you like between 0 and 9 (or 5 integers that you don't like, whatever) and make a list containing them. Save it in a variable called `secret_list`.
2. Forget everything you ever knew about the contents of `secret_list`.
3. Is `6` in `secret_list`? DON'T LOOK AT `secret_list` - use the `in` operator to check instead...
4. Make a new variable called `score`, and choose a score you want to start on. Whatever you like.
5. If `2` is in `secret_list`, add 2 to your score.
6. If the fourth element of `secret_list` is less than 3, or greater than or equal to 7, add 100 to your score; otherwise, take 100 away.
7. If the first element of `secret_list` is divisible by 3, multiply your score by 3. Else, if it's divisible by 4, multiply your score by 4. Else, divide your score by 2. (Hint: look up the **modulo operator**, `%`)
7. If `secret_list` contains 4 or 5 BUT NOT BOTH, square your score (`score**2`).
8. If you didn't use `if`-statements for each of steps 5-8, set `score` to 0 and start again from step 4. Else, you completed the game - good job! Impress your family/friends/colleagues by telling them your score.
9. Convert your score to a string. Use `in` to check whether it contains a `"1"`. If so... you _won_ the game! Impress your family/friends/colleagues again by telling them you won. Else, hard luck, but feel free to try again if you really really want to.

### 1.5 Repeating things

> "Repeat stuff, repeat stuff, repeat stuff, come on, louder, I can't hear you!" - Bo Burnham

Here are some numbers for you.

In [26]:
to_sum = [6, 23, 3, 12, 5, 19, 14]

Can you add them together?

"Wait a second, this isn't an exercise section!", you cry. Fine. Let's do it together.

In [40]:
total = to_sum[0] + to_sum[1] + to_sum[2] + to_sum[3] + to_sum[4] + to_sum[5] + to_sum[6]
total

82

Wooooow, that was a lot of typing. What if we had a list of 100 numbers to add together?

Really, what we need is a way of doing the same thing, over and over again...

In [41]:
total = 0

for k in to_sum:
    total = total + k

total

82

That was a **`for`-loop**, and everything happened rather fast... let's break it down:

* We **initialised** a variable called `total` with a value of `0`
* The `for` keyword, surprise surprise, told Python that we were about to write a `for`-loop
* Then we **iterated** over our list - that is:
    - We created a variable called `k`, and set it to be equal to the _first_ thing in `to_sum`, i.e. `6`
    - We ran the code within the `for`-loop using that value of `k`, i.e. we added `6` to `total`
    - Then we set `k` to be equal to the _second_ thing in `to_sum`, i.e. `23`
    - We ran the code within the `for`-loop using that value of `k`, i.e. we added `23` to `total`
    - Then we set `k` to be equal to the _third_ thing in `to_sum`...

So we started with a `total` of 0, then added `to_sum[0]`, then added `to_sum[1]`, and so on and so on, until we ran out of things in `to_sum`. Nifty.

Notice that in the process, we created a little helper variable called `k`. We don't really need it any more, but it's still lying around:

In [44]:
k

14

Why `14`? Because this was the last thing in `to_sum`, so this was the final value which we assigned to `k` (and subsequently added to `total`)!

In [45]:
to_sum[-1]

14

That helper variable didn't have to be called `k`. It's just like any other variable. We could have called it whatever we like! And we used it _in_ our loop, but we didn't have to...

In [46]:
n_elements = 0

for item in to_sum:
    n_elements = n_elements + 1
    
n_elements

7

If you know exactly how many times you want to do something, a `for`-loop is what you need. Say you're standing on the side of a hill. If you know that you want to take 1000 steps downhill, point yourself down the hill, and take 1000 steps. Simple.

Sometimes though, we know where we want to get to, but not necessarily how long it will take to get there. If you know that you want to get to the _bottom_ of the hill, then you point yourself downhill, and while you're still going downhill, you keep walking...

In [8]:
total = 1

while total < 1000:
    total = 2 * total

You might have been able to guess that this is called a **`while`-loop**: it's pretty similar to a `for`-loop, except while the condition is `True`, it keeps going. Which means you have to be slightly careful - because if your condition never switches to `False`, the loop will never stop, and you'll be stuck repeating the same thing forever and ever, until you're stopped by global warming/nuclear armageddon/Python running out of steam.

Any guesses for what `total` is equal to now? Go on, try to figure it out.

_[... patiently waits...]_

Aaaaand the correct answer is:

In [6]:
total

1024

Great job if you got that. If you didn't, you're probably convincing yourself that 1024 is definitely not less than 1000 and so WTF??! Has Python GONE WRONG?!?!

Spoiler alert: nope, Python's grand. We keep doubling `total`, so we start off with 1, 2, 4, 8, 16, 31, 64, 128, 256, 512. That last one is definitely still less than 1000, right? So our condition is `True`, so we run `total = 2*total`, so `total` gets set to 1024. And 1024 is NOT less than 1000, so our condition is `False`, so we quit the loop.

There's one other special way to quit either a `for`-loop or a `while`-loop early, before reaching the end. It's called **breaking**. Imagine you're walking down that hill again, intending to get to the bottom, but you find a nice bench and decide to stop walking to enjoy the view.

In [52]:
total = 1

while total < 1000:
    
    if (total % 17) == 0:
        break
        
    total = 2*total + 1

total

255

That loop was similar to the previous one, except if at some point we had a `total` which was divisible by 17 with remainder 0, we'd quit the loop at that point. That happened when we reached 255 (= 15\*17 + 0), so we stopped there.

#### Exercises

1. Write a `for`-loop that multiplies the elements of `to_sum`.
2. Adapt your loop so that it stops as soon as the total is more than 40.
3. Lists aren't the only things we can iterate over... what happens if you iterate over a string? Write a `for`-loop that calculates the length of a string.
4. Can you write a loop that keeps only the first word in a string? (Remember that you can add strings together...)

### 1.6 Things that make things

Imagine we're not sitting here in front of a computer, but instead we're in the kitchen. What we've done so far is basically just pull a load of stuff out of the cupboards and kinda spread it around, and we've mixed some stuff together, tasted some bits and pieces... which is great! We've learned loads, right?

But now we've learned about some of the basic ingredients, maybe it's time to stop throwing them around and instead do something useful with them. Maybe let's try following a recipe?

We've only just gotten started though, so let's not try anything too fancy. How about...

    Toast recipe
    ~~~~~~~~~~~~
    1. Put bread in toaster
    2. Let toaster do its thing
    3. Retrieve toast

Think about the role of the toaster here: it accepts the bread, does something to it, then gives it back to you.

Snap back to reality. That's exactly what a **function** does: it takes some input, does some stuff, and gives back some output. We've actually seen a couple of functions already...

In [ ]:
type(528491)

We provide the `type()` function with an object; it tells us the type. Or...

In [ ]:
str(1.21)

We give the `str()` function a numeric object; it turns it into a string and gives it back. Simple, right?

Let's look at a couple more functions...

In [35]:
len("A string")

8

What's `len()` doing?

Maybe you've figured it out already, but let's check the **documentation** to make sure:

In [36]:
?len

So `len()` gives us "the number of items in a container". Here, our "container" was actually a string, containing 8 characters. But we can use `len()` on different types of object - what about a list? Remember `letters` from earlier?

In [37]:
len(letters)

7

There's another function which we've actually been using a lot already, but so far it's been hiding very well. What do you think keeps making all our outputs magically appear under the code cells in this notebook?

In [38]:
print("Hi, it was me!")

Hi, it was me!


Let's read a bit more about `print()`.

In [39]:
?print

The first line of the documentation shows us a template of how to use `print()`. Notice the commas?

So far, we've only been putting one **argument** into these functions - one number, or one string, or one list. But functions don't necessarily have to have only 1 argument!

In [40]:
print("Here are", 3, "different arguments!")

Here are 3 different arguments!


Those three arguments (`"Here are"`, `3` and `"different arguments!"`) were all **unnamed**: we just threw them in, and `print()`... well, it printed them! But see how it joined the three arguments together with a space in between, and then printed them as a single string.

But what if we didn't want those arguments to be separated by a space? Well, we can tell `print()` to use a different separator...

In [41]:
print("Here are", 3, "different arguments!", sep="@")

Here are@3@different arguments!


In that call to `print()`, we used a **named argument**: we set `sep` to be a particular string (`"@"`).

Looking again at the documentation for `print()`, notice that `sep` has a **default value** of `sep=' '`. That means unless we specify `sep` as something different, then `print()` will use a string containing a single space (`' '`) as the separator between words - this is exactly what was happening before!

Wait, so... how come sometimes we use named arguments, and sometimes we don't?

Like most programming languages, Python uses two things to decide which arguments we've given a function:
1. Name - if you use the argument name, Python will absolutely definitely know which argument you've given it!
2. Position - if you don't use a name, Python has to guess



In [27]:
?range

*Exercise*: print the following

    a
    a-b
    a-b-c
    a-b-c-d
    a-b-c-d-e
    a-b-c-d-e-f

In [ ]:
for k in range(len(letters)):
    joined_letters = "-".join(letters[:(k+1)])
    print(joined_letters)

In [ ]:
import numpy as np

#### Exercises

1. Make a list containing 5 things, and check the length with `len()`
2. Use `print()` to print a string containing the days of the week, separated by a dollar sign
3. Print that string again, but use the `end` argument to append another string of your choice

### 1.7 Making things that make things

OK, so we can use functions which already exist in Python. 

In [43]:
def say(phrase, who="Me"):
    to_print = who + ": " + phrase
    print(to_print)

In [44]:
say("Hello!")

Me: Hello!


In [45]:
say("Hello there!", who="Obi-Wan")

Obi-Wan: Hello there!


In [46]:
def say_multi(phrases, who="Me"):
    lines = [who + ": " + phrase for phrase in phrases]
    to_print = "\n".join(lines)
    print(to_print)

In [47]:
say_multi(["Hello!", "Is it me you're looking for?"], who="Lionel")

Lionel: Hello!
Lionel: Is it me you're looking for?


In [48]:
def grade(score):
    if (score >= 40):
        print("Pass")
    else:
        print("Fail")

In [49]:
grade(80)

Pass


In [50]:
grade(39.999)

Fail


> "If you want to be a writer, you must do two things above all others: read a lot and write a lot. There's no way around these two things that I'm aware of, no shortcut." - Stephen King

## Exercise solutions

In [51]:
# 1.1
"hi" + "there"
3 * "hi"
type(3/2)

float

In [52]:
# 1.2
python_ability = 1

python_ability = python_ability + 1
python_ability

"Right now my Python ability is " + str(python_ability) + " and I am freaking awesome!"

["hello", 42, [101010, "listception"]]

letters[0:6:2]
letters[::-1]

['g', 'f', 'e', 'd', 'c', 'b', 'a']

In [53]:
# 1.3
True + True + False
5 + True

"aa" == "aaAAA"

"p" > "m"
"pb" > "pa"

True

In [24]:
# 1.4
secret_list = [1, 2, 5, 6, 8]

6 in secret_list

score = 21

if 2 in secret_list:
    score = score + 2

if secret_list[3] < 3 or secret_list[3] >= 7:
    score = score + 100
else:
    score = score - 100

if secret_list[0] % 3 == 0:
    score = score * 3
elif secret_list[0] % 4 == 0:
    score = score * 4
else:
    score = score / 2

if (4 in secret_list or 5 in secret_list) and not (4 in secret_list and 5 in secret_list):
    score = score**2

score, "1" in str(score)

(1482.25, True)

In [33]:
# 1.5
product = 1

for k in to_sum:
    product = product * k

    
product = 1

for k in to_sum:
    if product > 5000:
        break
    product = product * k


message = "This is a nice message"
nchar = 0

for letter in message:
    nchar = nchar + 1


first_word = ""

for letter in message:
    
    if letter == " ":
        break
        
    first_word = first_word + letter

first_word

'This'